-- MySQL Script generated by MySQL Workbench
-- 11/28/16 17:11:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`fsm_country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fsm_country` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fsm_country` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fsm_city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fsm_city` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fsm_city` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `country_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_country_idx` (`country_id` ASC),
  CONSTRAINT `fk_city_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`fsm_country` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fsm_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fsm_location` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fsm_location` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `city_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `location_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_location_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_location_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`fsm_city` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fsm_floor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fsm_floor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fsm_floor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `location_id` INT(11) NOT NULL,
  `floor_code` VARCHAR(45) NOT NULL,
  `min_x` INT(11) NOT NULL,
  `min_y` INT(11) NOT NULL,
  `max_x` INT(11) NOT NULL,
  `max_y` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_floor_location1_idx` (`location_id` ASC),
  CONSTRAINT `fk_floor_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`fsm_location` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fsm_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fsm_table` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fsm_table` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `floor_id` INT(11) NOT NULL,
  `top_left_x` INT(11) NOT NULL,
  `top_left_y` INT(11) NOT NULL,
  `length` INT(11) NOT NULL,
  `width` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_table_floor1_idx` (`floor_id` ASC),
  CONSTRAINT `fk_table_floor1`
    FOREIGN KEY (`floor_id`)
    REFERENCES `mydb`.`fsm_floor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fsm_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fsm_group` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fsm_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `parent_group_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group_group1_idx` (`parent_group_id` ASC),
  CONSTRAINT `fk_group_group1`
    FOREIGN KEY (`parent_group_id`)
    REFERENCES `mydb`.`fsm_group` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fsm_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fsm_employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fsm_employee` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `brid` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `group_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `brid_UNIQUE` (`brid` ASC),
  INDEX `fk_employee_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_employee_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `mydb`.`fsm_group` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fsm_desk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fsm_desk` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fsm_desk` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `table_id` INT(11) NOT NULL,
  `employee_id` INT(11) NULL,
  `table_row` INT(11) NOT NULL,
  `table_col` INT(11) NOT NULL,
  `desk_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_desk_table1_idx` (`table_id` ASC),
  INDEX `fk_desk_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_desk_table1`
    FOREIGN KEY (`table_id`)
    REFERENCES `mydb`.`fsm_table` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_desk_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`fsm_employee` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fsm_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fsm_role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fsm_role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fsm_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fsm_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fsm_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `employee_id` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_employee1_idx` (`employee_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`fsm_employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`fsm_role` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`fsm_country`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`fsm_country` (`name`) VALUES ('India');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`fsm_city`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`fsm_city` (`country_id`, `name`) VALUES (1, 'Pune');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`fsm_location`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`fsm_location` (`city_id`, `name`, `location_code`) VALUES (1, 'Kharadi', 'P3');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`fsm_floor`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`fsm_floor` (`location_id`, `floor_code`, `min_x`, `min_y`, `max_x`, `max_y`) VALUES (1, 'L2', 0, 0, 100, 100);
INSERT INTO `mydb`.`fsm_floor` (`location_id`, `floor_code`, `min_x`, `min_y`, `max_x`, `max_y`) VALUES (1, 'L3', -1, -1, -1, -1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`fsm_table`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`fsm_table` (`floor_id`, `top_left_x`, `top_left_y`, `length`, `width`) VALUES (1, 20, 20, 3, 2);
INSERT INTO `mydb`.`fsm_table` (`floor_id`, `top_left_x`, `top_left_y`, `length`, `width`) VALUES (1, 40, 50, 2, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`fsm_desk`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`fsm_desk` (`table_id`, `employee_id`, `table_row`, `table_col`, `desk_code`) VALUES (1, NULL, 1, 1, '2-101');
INSERT INTO `mydb`.`fsm_desk` (`table_id`, `employee_id`, `table_row`, `table_col`, `desk_code`) VALUES (1, NULL, 1, 2, '2-102');
INSERT INTO `mydb`.`fsm_desk` (`table_id`, `employee_id`, `table_row`, `table_col`, `desk_code`) VALUES (1, NULL, 2, 1, '2-103');
INSERT INTO `mydb`.`fsm_desk` (`table_id`, `employee_id`, `table_row`, `table_col`, `desk_code`) VALUES (1, NULL, 2, 2, '2-104');
INSERT INTO `mydb`.`fsm_desk` (`table_id`, `employee_id`, `table_row`, `table_col`, `desk_code`) VALUES (1, NULL, 2, 3, '2-105');
INSERT INTO `mydb`.`fsm_desk` (`table_id`, `employee_id`, `table_row`, `table_col`, `desk_code`) VALUES (2, NULL, 1, 1, '2-106');
INSERT INTO `mydb`.`fsm_desk` (`table_id`, `employee_id`, `table_row`, `table_col`, `desk_code`) VALUES (2, NULL, 1, 2, '2-107');
INSERT INTO `mydb`.`fsm_desk` (`table_id`, `employee_id`, `table_row`, `table_col`, `desk_code`) VALUES (2, NULL, 1, 3, '2-108');
INSERT INTO `mydb`.`fsm_desk` (`table_id`, `employee_id`, `table_row`, `table_col`, `desk_code`) VALUES (2, NULL, 2, 1, '2-109');
INSERT INTO `mydb`.`fsm_desk` (`table_id`, `employee_id`, `table_row`, `table_col`, `desk_code`) VALUES (2, NULL, 2, 2, '2-110');
INSERT INTO `mydb`.`fsm_desk` (`table_id`, `employee_id`, `table_row`, `table_col`, `desk_code`) VALUES (2, NULL, 2, 3, '2-111');

COMMIT;

